version: '3.8'
services:
  app:
    build: .
    container_name: go-react-framework
    ports:
      - "8080:8080"
      - "3001:3001"
    volumes:
      - pnpm-store:/app/node_modules/.pnpm-store
    restart: always
    environment:
      - NODE_ENV=production
    # Uncomment if you want to override entrypoint or pass extra args
    # entrypoint: ["./docker-entrypoint.sh"]

volumes:
  pnpm-store:
    driver: local 